### ISSUE TITLE
Prez not starting - Looking for CetPrez when not enabled

### ISSUE THREAD

**Issue by KoalaGeo** [RDFLib/prez#77]
Hi, 

Trying to test Prez on k8s but I'm getting a 502. 

Logs:
`HTTP Exception for / - Request URL missing either an 'http://' or 'https://' protocol. Failed to connect to CatPrez endpoint.`

I've not enabled CatPrez - my deployment spec is below: 
```
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: ${KUBE_NAMESPACE}
        image: ghcr.io/rdflib/prez:2.6  
        env:
        - name: PREZ_TITLE
          value: "BGS Linked Data API"
          name: ENABLED_PREZS
          value: '["VocPrez"]' #'["SpacePrez","VocPrez"]'
          #name: SPACEPREZ_SPARQL_ENDPOINT
          #value: http://some-sparql-endpoint.com/sparql
          name: VOCPREZ_SPARQL_ENDPOINT
          value: https://vocabs.gsq.digital/sparql/
          name: VOCPREZ_TITLE
          value: "BGS VocPrez"
          #name: SPACEPREZ_TITLE
          #value: "BGS SpacePrez"
        imagePullPolicy: Always
        ports:
        - containerPort: ${CONTAINER_PORT}
```
I've tried enabling CatPrez & setting an endpoint but still get the same error

```
containers:
      - name: ${KUBE_NAMESPACE}
        image: ghcr.io/rdflib/prez:2.6  
        env:
        - name: PREZ_TITLE
          value: "BGS Linked Data API"
          name: ENABLED_PREZS
          value: '["CatPrez","VocPrez"]' 
          #name: SPACEPREZ_SPARQL_ENDPOINT
          #value: http://some-sparql-endpoint.com/sparql
          name: VOCPREZ_SPARQL_ENDPOINT
          value: https://vocabs.gsq.digital/sparql
          name: CATPREZ_SPARQL_ENDPOINT
          value: https://vocabs.gsq.digital/sparql
          name: VOCPREZ_TITLE
          value: "BGS VocPrez"
```

Any suggestions?
